spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://orders_db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/gustavoedev

server:
  port: 8081