server:
  port: 9000

spring:
  application:
    name: Gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/gustavoedev

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ordersapi
              uri: http://ordersapi:8081
              predicates:
                - Path=/order/**
              filters:
                - TokenRelay